CREATE TABLE IF NOT EXISTS states (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    abbreviation VARCHAR(2) NOT NULL PRIMARY KEY,
    capital VARCHAR(100),
    timezone VARCHAR(50)
);

INSERT INTO states (name, abbreviation, capital, timezone) VALUES
('Alabama', 'AL', 'Montgomery', 'Central'),
('Alaska', 'AK', 'Juneau', 'Alaska'),
('Arizona', 'AZ', 'Phoenix', 'Mountain'),
('Arkansas', 'AR', 'Little Rock', 'Central'),
('California', 'CA', 'Sacramento', 'Pacific'),
('Colorado', 'CO', 'Denver', 'Mountain'),
('Connecticut', 'CT', 'Hartford', 'Eastern'),
('Delaware', 'DE', 'Dover', 'Eastern'),
('Florida', 'FL', 'Tallahassee', 'Eastern'),
('Georgia', 'GA', 'Atlanta', 'Eastern'),
('Hawaii', 'HI', 'Honolulu', 'Hawaii-Aleutian'),
('Idaho', 'ID', 'Boise', 'Mountain'),
('Illinois', 'IL', 'Springfield', 'Central'),
('Indiana', 'IN', 'Indianapolis', 'Eastern'),
('Iowa', 'IA', 'Des Moines', 'Central'),
('Kansas', 'KS', 'Topeka', 'Central'),
('Kentucky', 'KY', 'Frankfort', 'Eastern'),
('Louisiana', 'LA', 'Baton Rouge', 'Central'),
('Maine', 'ME', 'Augusta', 'Eastern'),
('Maryland', 'MD', 'Annapolis', 'Eastern'),
('Massachusetts', 'MA', 'Boston', 'Eastern'),
('Michigan', 'MI', 'Lansing', 'Eastern'),
('Minnesota', 'MN', 'Saint Paul', 'Central'),
('Mississippi', 'MS', 'Jackson', 'Central'),
('Missouri', 'MO', 'Jefferson City', 'Central'),
('Montana', 'MT', 'Helena', 'Mountain'),
('Nebraska', 'NE', 'Lincoln', 'Central'),
('Nevada', 'NV', 'Carson City', 'Pacific'),
('New Hampshire', 'NH', 'Concord', 'Eastern'),
('New Jersey', 'NJ', 'Trenton', 'Eastern'),
('New Mexico', 'NM', 'Santa Fe', 'Mountain'),
('New York', 'NY', 'Albany', 'Eastern'),
('North Carolina', 'NC', 'Raleigh', 'Eastern'),
('North Dakota', 'ND', 'Bismarck', 'Central'),
('Ohio', 'OH', 'Columbus', 'Eastern'),
('Oklahoma', 'OK', 'Oklahoma City', 'Central'),
('Oregon', 'OR', 'Salem', 'Pacific'),
('Pennsylvania', 'PA', 'Harrisburg', 'Eastern'),
('Rhode Island', 'RI', 'Providence', 'Eastern'),
('South Carolina', 'SC', 'Columbia', 'Eastern'),
('South Dakota', 'SD', 'Pierre', 'Central'),
('Tennessee', 'TN', 'Nashville', 'Central'),
('Texas', 'TX', 'Austin', 'Central'),
('Utah', 'UT', 'Salt Lake City', 'Mountain'),
('Vermont', 'VT', 'Montpelier', 'Eastern'),
('Virginia', 'VA', 'Richmond', 'Eastern'),
('Washington', 'WA', 'Olympia', 'Pacific'),
('West Virginia', 'WV', 'Charleston', 'Eastern'),
('Wisconsin', 'WI', 'Madison', 'Central'),
('Wyoming', 'WY', 'Cheyenne', 'Mountain');